---
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.19
    hooks:
      - id: markdown-link-check
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt
        always_run: true
