name: "On commit"

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  binary:
    name: Binary
    strategy:
      fail-fast: true
      matrix:
        goos:
          - linux
        goarch:
          - amd64
          - arm64
    uses: PossibleLlama/workflows/.github/workflows/golang-binary.yaml@v0.2.19
    with:
      source-path: "./exec/cli/main.go"
      build-flags: "-ldflags=\"-w -s\""
      os: ${{ matrix.goos }}
      arch: ${{ matrix.goarch }}
      binary-prefix: "Binaries-cli-"

  server:
    name: Server
    strategy:
      fail-fast: true
      matrix:
        goos:
          - linux
        goarch:
          - amd64
          - arm64
    uses: PossibleLlama/workflows/.github/workflows/golang-binary.yaml@v0.2.19
    with:
      source-path: "./exec/server/main.go"
      build-flags: "-ldflags=\"-w -s\""
      os: ${{ matrix.goos }}
      arch: ${{ matrix.goarch }}
      binary-prefix: "Binaries-server-"

  linting:
    name: Linting
    uses: PossibleLlama/workflows/.github/workflows/golang-linting.yaml@v0.2.19
    with:
      source-path: "./exec/cli/main.go"

  test-small:
    name: Test small
    uses: PossibleLlama/workflows/.github/workflows/golang-testing-small.yaml@v0.2.19
    with:
      enable-performance: true
      enable-fuzz: false
