name: "On commit - Main"

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  binary:
    name: Binary
    strategy:
      fail-fast: false
      matrix:
        goos:
          - linux
          - darwin
          - windows
        goarch:
          - amd64
          - arm64
    uses: PossibleLlama/workflows/.github/workflows/golang-binary.yaml@v0.2.8
    with:
      source-path: "./exec/cli/main.go"
      build-flags: "-ldflags=\"-w -s\""
      os: ${{ matrix.goos }}
      arch: ${{ matrix.goarch }}
      binary-prefix: "Binaries-cli-"
      retention-days: 30

  server:
    name: Server
    strategy:
      fail-fast: false
      matrix:
        goos:
          - linux
          - darwin
          - windows
        goarch:
          - amd64
          - arm64
    uses: PossibleLlama/workflows/.github/workflows/golang-binary.yaml@v0.2.8
    with:
      source-path: "./exec/server/main.go"
      build-flags: "-ldflags=\"-w -s\""
      os: ${{ matrix.goos }}
      arch: ${{ matrix.goarch }}
      binary-prefix: "Binaries-server-"
      retention-days: 30

  security:
    name: Security checks
    permissions:
      security-events: write
    uses: PossibleLlama/workflows/.github/workflows/golang-security.yaml@v0.2.8
    with:
      upload-sarif: true

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - binary
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"

    - name: Download app
      uses: actions/download-artifact@v4
      with:
        path: .

    - name: Move binaries
      run: |
        mv ./Binaries-cli-darwin-amd64/* .
        mv ./Binaries-cli-darwin-arm64/* .
        mv ./Binaries-cli-linux-amd64/* .
        mv ./Binaries-cli-linux-arm64/* .
        mv ./Binaries-cli-windows-amd64/* .
        mv ./Binaries-cli-windows-arm64/* .
        mv ./Binaries-server-darwin-amd64/* .
        mv ./Binaries-server-darwin-arm64/* .
        mv ./Binaries-server-linux-amd64/* .
        mv ./Binaries-server-linux-arm64/* .
        mv ./Binaries-server-windows-amd64/* .
        mv ./Binaries-server-windows-arm64/* .

    - name: Semantic Release
      run: |
        npm i @semantic-release/commit-analyzer @semantic-release/git @semantic-release/changelog conventional-changelog-conventionalcommits
        npx semantic-release@21
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
