name: "On commit"

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: make deps

    - name: Build
      run: make build-local

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Check formatting
      run: make format

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    # This is how the e2e tests are ran
    - name: Install commander
      run: go install github.com/commander-cli/commander/v2/cmd/commander@latest

    - name: Get dependencies
      run: make deps

    - name: Test once
      run: make test

    - name: Test multiple
      run: make test-repeat
