name: "On commit to main"

on:
  workflow_run:
    workflows: ["On commit"]
    branches: [main]
    types: [completed]

jobs:
  store:
    name: Store artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: make deps

    - name: Compile
      run: make compile

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: worklog-binary
        path: bin
