name: "On commit to main"

on:
  workflow_run:
    workflows: ["On commit"]
    branches: [main]
    types: [completed]

jobs:
  binaries:
    name: Generate binaries
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: make deps

    - name: Generate binaries
      run: make compile

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: worklog-binary
        path: bin

  run-ubuntu:
    name: Run-ubuntu
    runs-on: ubuntu-latest
    needs: [binaries]

    strategy:
      matrix:
        binary:
          - "32bit/worklog-linux"
          - "64bit/worklog-linux"

    steps:
    - name: Download
      uses: actions/download-artifact@v2
      with:
        name: worklog-binary

    - name: Permissions
      run: "sudo chown -R $USER:$USER ./32bit ./64bit && sudo chmod +x 32bit/worklog-* 64bit/worklog-*"

    - name: Extract
      run: "mv ./${{ matrix.binary }} ./worklog"

    # TODO change to tests
    - name: Test
      run: "./worklog"

  run-mac:
    name: Run-mac
    runs-on: macos-latest
    needs: [binaries]

    strategy:
      matrix:
        binary:
          - "64bit/worklog-darwin"

    steps:
    - name: Download
      uses: actions/download-artifact@v2
      with:
        name: worklog-binary

    - name: Permissions
      run: "sudo chown -R $USER ./32bit ./64bit && sudo chmod +x 32bit/worklog-* 64bit/worklog-*"

    - name: Extract
      run: "mv ./${{ matrix.binary }} ./worklog"

    - name: Test
      run: "./worklog"

  run-windows:
    name: Run-windows
    runs-on: windows-latest
    needs: [binaries]

    strategy:
      matrix:
        binary:
          - "32bit\\worklog-windows.exe"
          - "64bit\\worklog-windows.exe"

    steps:
    - name: Download
      uses: actions/download-artifact@v2
      with:
        name: worklog-binary

    - name: Extract
      run: "move .\\${{ matrix.binary }} .\\worklog.exe"

    - name: Test
      run: ".\\worklog.exe"

  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Generate changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        output: release-changelog.txt

    - name: Archive changelog artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-changelog
        path: release-changelog.txt

  release:
    name: Generate release
    runs-on: ubuntu-latest
    needs:
      - binaries
      - changelog
      - run-ubuntu
      - run-mac
      - run-windows

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Download binary
      uses: actions/download-artifact@v2
      with:
        name: worklog-binary

    - name: Zip binaries
      run: "zip binaries.zip 32bit 64bit"

    - name: Download changelog
      uses: actions/download-artifact@v2
      with:
        name: release-changelog

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: binaries.zip
        body_path: release-changelog.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
