name: "Milestone closing"

on:
  milestone:
    types: [closed]

jobs:
  generate-tag:
    name: Generate tag
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Push tag
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ github.event.milestone.title }}
