# https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code
name: "CodeQL"

on:
  schedule:
    - cron: "30 07 * * 5"

jobs:
  security:
    name: Security checks
    permissions:
      security-events: write
    uses: PossibleLlama/workflows/.github/workflows/golang-security.yaml@v0.2.5
    with:
      upload-sarif: true
