name: "Security scans"

on: push

jobs:
  SCA:
    name: SCA
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Write Go List
      run: go list -json -m all > go.list

    - name: Run Nancy
      uses: sonatype-nexus-community/nancy-github-action@main

  SAST:
    name: SAST
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
